#### Issue summary

icalc.py function failure (do_rem)

#### Issue description

In icalc.py the function do_rem gives false result. Can be caused by wrong function calling. (self.cal.div())
Might be similar to issue #1(bug_report_1.txt)

#### Steps to reproduce the issue

1.  Run icalc.py 
2.  Call do_rem with any arguments 

#### Expected result

5%2 = 1

#### Actual result

2.5

#### Priority

1

#### Severity

Major

#### Created by

Máté, Kósa

#### Creation date

2022.06.19 